DROP DATABASE IF EXISTS SKYSTREAM;
CREATE DATABASE SKYSTREAM;
USE SKYSTREAM;

CREATE TABLE USUARIOS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  passw0rd VARCHAR(255) NOT NULL,
  email VARCHAR(45) NOT NULL,
  rol VARCHAR(45)
);